"""Opt-in real-account smoke test. Never runs unless explicitly enabled."""

import os
import uuid

import pytest

from apple_reminders_mcp.config import Settings
from apple_reminders_mcp.reminders import RemindersService

pytestmark = pytest.mark.skipif(
    os.getenv("RUN_ICLOUD_INTEGRATION_TESTS", "false").lower() != "true",
    reason="real iCloud integration tests are opt-in",
)


def test_designated_list_round_trip():
    list_id = os.getenv("ICLOUD_TEST_REMINDER_LIST_ID", "").strip()
    if not list_id:
        pytest.fail("ICLOUD_TEST_REMINDER_LIST_ID must name the dedicated test list")
    svc = RemindersService(Settings.from_env())
    created_id = None
    try:
        assert any(row["list_id"] == list_id for row in svc.list_lists())
        created = svc.create(
            "Apple-Reminders-MCP integration test",
            list_id,
            description="Generated by the explicit live integration test",
            request_id=f"live-{uuid.uuid4()}",
        )
        created_id = created["reminder_id"]
        assert svc.update(created_id, flagged=True)["flagged"] is True
        assert svc.complete(created_id, True)["completed"] is True
        assert svc.complete(created_id, False)["completed"] is False
        assert svc.add_tag(created_id, "MCPIntegrationTest")["tag"]["name"]
        assert svc.add_url(created_id, "https://example.com/")["type"] == "url"
        recurrence = svc.set_recurrence(created_id, "weekly")
        assert recurrence["frequency"] == "weekly"
        assert svc.clear_recurrence(created_id)["cleared"] is True
        prepared = svc.prepare_delete(created_id)
        assert svc.confirm_delete(prepared["confirmation_token"])["deleted"] is True
        created_id = None
    finally:
        if created_id:
            try:
                svc.reminders.delete(svc.reminders.get(created_id))
            except Exception:
                print(f"Manual cleanup required for exact Reminder ID: {created_id}")
